### ISSUE TITLE
Issues running demo application

### ISSUE THREAD

**Issue by collinforrester** [anchan828/nest-cloud-run-queue#1043]
Hi,

Awesome library & information.  I'm trying to test out a few things locally like creating a stand alone NestJS application that I can run as a separate service on cloud run.  To do this I wanted to use your included demo code but I'm having quite a few issues getting it up and running.

The latest is 

 Error: Cannot find module '/work/node_modules/@anchan828/nest-cloud-run-queue-pubsub-publisher/dist/index.js'. Please verify that the package.json has a valid "main" entry
nest-cloud-run-queue-demo-1                    |     at tryPackage (node:internal/modules/cjs/loader:364:19)
nest-cloud-run-queue-demo-1                    |     at Function.Module._findPath (node:internal/modules/cjs/loader:577:18)
nest-cloud-run-queue-demo-1                    |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
nest-cloud-run-queue-demo-1                    |     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
nest-cloud-run-queue-demo-1                    |     at Module.require (node:internal/modules/cjs/loader:1022:19)
nest-cloud-run-queue-demo-1                    |     at require (node:internal/modules/cjs/helpers:102:18)
nest-cloud-run-queue-demo-1                    |     at Object.<anonymous> (/work/packages/demo/src/app.module.ts:2:1)
nest-cloud-run-queue-demo-1                    |     at Module._compile (node:internal/modules/cjs/loader:1120:14)
nest-cloud-run-queue-demo-1                    |     at Module._compile (/work/node_modules/source-map-support/source-map-support.js:568:25)
nest-cloud-run-queue-demo-1                    |     at Module.m._compile (/tmp/ts-node-dev-hook-9765870059263038.js:69:33)

I'm not sure if I'm missing a step maybe.  I followed the instructions in the README - npm i & docker-compose up.

**Comment by anchan828** [comment]
Hi @collinforrester,　Thanks for trying this package.

When run `npm install` under the demo directory, it is trying to get the package from the npmjs registry instead of a symbolic link. The explanation was insufficient, so I have made improvements.

https://github.com/anchan828/nest-cloud-run-queue/commit/fb66cdd10c392ed470e7ad248db6edbb0b7018cd

Try removing node_modules once and running `docker-compose up` again.　`npm i` is no longer needed.

**Comment by anchan828** [comment]
If you have any problems, please create an Issue again.
