### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by ftognetto** [anchan828/nest-cloud-run-queue#1058]
Hi @anchan828  thanks for this library, it is just what I was looking for!
There is something that maybe I'm missing, I need to send messages from cloud run on pub sub and then to receive messages on cloud run through a push subscription and it seems to me that this library does just that.
But does the subscription have to be created by hand or is it created from your library?
Thanks again

**Comment by anchan828** [comment]
Hi @ftognetto, 
If you use Cloud Pub/Sub or Tasks, you will need to configure the settings manually. This Library does not subscribe automatically as it merely receives HTTP requests.
