### ISSUE TITLE
Local BackUp delivery / Development

### ISSUE THREAD

**Issue by paulwer** [anchan828/nest-cloud-run-queue#1710]
Hey folks,
nice package. Is there a way to integrate event-emitter package or similar on dev to give the option to develop a local working version, without have the dependencie of working with google cloud.

We want to test our applications local, so this would be a great addition :)

Best regards
Paul

**Comment by anchan828** [comment]
Hi @paulwer, There are emulators for pubsub and tasks. Could these be used to meet your requirements?

My demo app is running on an emulator.　See:
https://github.com/anchan828/nest-cloud-run-queue/blob/master/docker-compose.yml

**Comment by paulwer** [comment]
great suggestion, can you add this to the readme. 
I guess this would be a great improvements for new users :)

Thank you

**Comment by anchan828** [comment]
Thanks for the suggestion. It is simple but I added the text.
https://github.com/anchan828/nest-cloud-run-queue/commit/130daff0bf812870a7d9ae34ce968bcc2d6eed11
