### ISSUE TITLE
Warning at startup - long startup

### ISSUE THREAD

**Issue by paulwer** [anchan828/nest-cloud-run-queue#1711]
WARN [ModuleTokenFactory] The module "TasksPublisherModule" is taking 1402.12ms to serialize, this may be caused by larger objects statically assigned to the module. More details: https://github.com/nestjs/nest/issues/12738 +1407ms

any suggestions?

**Comment by anchan828** [comment]
Hi @paulwer, Thanks for the report. I have fixed this issue. Please use the new version.

https://github.com/anchan828/nest-cloud-run-queue/releases/tag/v2.1.0
